/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author Andrew
 */
public class Contato extends javax.swing.JFrame {

    /**
     * Creates new form Contato
     */
    public Contato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMenu1 = new javax.swing.JButton();
        jButtonUsar = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jButtonProjeto = new javax.swing.JButton();
        jButtonOnuView = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMenu1.setBorder(null);
        jButtonMenu1.setContentAreaFilled(false);
        jButtonMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenu1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 60, 30));

        jButtonUsar.setBorder(null);
        jButtonUsar.setContentAreaFilled(false);
        jButtonUsar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUsar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 120, 30));

        jButtonLogOut.setBorder(null);
        jButtonLogOut.setContentAreaFilled(false);
        jButtonLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 20, 40, 40));

        jButtonProjeto.setBorder(null);
        jButtonProjeto.setContentAreaFilled(false);
        jButtonProjeto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjetoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, 70, 30));

        jButtonOnuView.setBorder(null);
        jButtonOnuView.setContentAreaFilled(false);
        jButtonOnuView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOnuView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOnuViewActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOnuView, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 560, 520));

        jButtonMenu.setBorder(null);
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, 30));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 30, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resoucer/Contato.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenu1ActionPerformed
        
        MenuView menuView = new MenuView();
        this.setVisible(false);
        menuView.setVisible(true);
    }//GEN-LAST:event_jButtonMenu1ActionPerformed

    private void jButtonUsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsarActionPerformed
       UsarView usarView = new UsarView();
       this.setVisible(false);
       usarView.setVisible(true);
    }//GEN-LAST:event_jButtonUsarActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        LoginView loginView = new LoginView();
        this.setVisible(false);
        loginView.setVisible(true);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonOnuViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOnuViewActionPerformed
                try {
            URI link = new URI("https://brasil.un.org/pt-br/sdgs");
            Desktop.getDesktop().browse(link);
        }catch(Exception erro){
            System.err.println(erro);
        }
    }//GEN-LAST:event_jButtonOnuViewActionPerformed

    private void jButtonProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjetoActionPerformed
        ProjetoView projetoView = new ProjetoView();
        this.setVisible(false);
        projetoView.setVisible(true);
    }//GEN-LAST:event_jButtonProjetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonMenu1;
    private javax.swing.JButton jButtonOnuView;
    private javax.swing.JButton jButtonProjeto;
    private javax.swing.JButton jButtonUsar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
